import {expect,it,vi} from 'vitest';
import {createNarrationStore} from '../../frontend/src/stores/narration';
const context:any={mode:'narration_first_v1',source_script_record_id:'s',source_text_sha256:'a'.repeat(64),configuration_revision:1,target_duration_band:{minMs:1000,maxMs:5000},options:[],configuration:{creative:{},video:{},capabilities:{}}};
function setup(){let project='p';const api:any={context:vi.fn(async()=>context),snapshot:vi.fn(async()=>({project_id:project,narration_readiness:{ready:false},latest_narration_candidate:null})),detail:vi.fn(),generate:vi.fn(async()=>({narration_record_id:'n'})),confirmScript:vi.fn(),confirm:vi.fn(),cancel:vi.fn(),save:vi.fn()};return {api,setProject:(p:string)=>project=p,store:createNarrationStore({projectId:()=>project,api,keyStore:new Map()})};}
it('重复点击只发一次，网络失败重试同key',async()=>{const f=setup();await f.store.refresh();f.api.generate.mockRejectedValueOnce(Error('network'));await Promise.all([f.store.generate(),f.store.generate()]);expect(f.api.generate).toHaveBeenCalledTimes(1);const key=f.api.generate.mock.calls[0][1].idempotency_key;await f.store.generate();expect(f.api.generate.mock.calls[1][1].idempotency_key).toBe(key);});
it('URL存在不能代替后端readiness',async()=>{const f=setup();await f.store.refresh();expect(f.store.canProceed()).toBe(false);f.api.snapshot.mockResolvedValue({project_id:'p',narration_readiness:{ready:true}});await f.store.refresh();expect(f.store.canProceed()).toBe(true);});
it('项目切换后旧刷新不得覆盖新项目',async()=>{const f=setup();let resolve:any;f.api.context.mockImplementationOnce(()=>new Promise(r=>resolve=r));const old=f.store.refresh();f.setProject('q');await f.store.refresh();resolve({...context,source_script_record_id:'old'});await old;expect(f.store.state.projectId).toBe('q');expect(f.store.state.context?.source_script_record_id).toBe('s');});
it('刷新恢复服务端候选状态',async()=>{const f=setup();f.api.snapshot.mockResolvedValue({project_id:'p',latest_narration_candidate:{narration_record_id:'n'}});f.api.detail.mockResolvedValue({record:{id:'n'},effective_status:'unknown',files:null});await f.store.refresh();expect(f.store.state.detail?.effective_status).toBe('unknown');expect(f.api.generate).not.toHaveBeenCalled();});

for(const status of ['unknown','failed'])it('恢复已接受终态后显式重生创建新key '+status,async()=>{const f=setup();await f.store.refresh();f.api.generate.mockRejectedValueOnce(Error('network'));await f.store.generate();const key=f.api.generate.mock.calls[0][1].idempotency_key;f.api.snapshot.mockResolvedValue({project_id:'p',latest_narration_candidate:{narration_record_id:'n'}});f.api.detail.mockResolvedValue({record:{id:'n',sourceTextSha256:context.source_text_sha256},effective_status:status,idempotency_key:key,files:null});await f.store.refresh();await f.store.generate();expect(f.api.generate.mock.calls[1][1].idempotency_key).not.toBe(key);});

for(const terminal of ['failed','cancelled','unknown'])it('候选终止后可选择active零TTS重新接受 '+terminal,async()=>{const f=setup();f.api.snapshot.mockResolvedValue({project_id:'p',active_narration:{narration_record_id:'a'},latest_narration_candidate:{narration_record_id:'b'},narration_readiness:{ready:false,reason:'narration_duration_not_accepted'}});f.api.detail.mockImplementation(async(_p:string,id:string)=>({record:{id,sourceTextSha256:context.source_text_sha256,settingsSha256:'b'.repeat(64)},effective_status:id==='a'?'confirmed':terminal,files:null}));await f.store.refresh();expect(f.store.state.detail?.record.id).toBe('b');await f.store.selectRecord('a');expect(f.store.state.detail?.record.id).toBe('a');await f.store.confirm(true);expect(f.api.confirm).toHaveBeenCalledWith('p','a',expect.objectContaining({accept_duration_outside_band:true}));expect(f.api.generate).not.toHaveBeenCalled();await f.store.refresh();expect(f.store.state.detail?.record.id).toBe('a');});

for(const [from,to] of [['b','a'],['a','b']])it('切换详情加载期间禁止旧版本确认和取消 '+from+'→'+to,async()=>{const f=setup();f.api.snapshot.mockResolvedValue({project_id:'p',active_narration:{narration_record_id:'a'},latest_narration_candidate:{narration_record_id:'b'}});const detail=(id:string)=>({record:{id,sourceTextSha256:context.source_text_sha256,settingsSha256:'b'.repeat(64)},effective_status:id==='a'?'confirmed':'ready',files:null});f.api.detail.mockImplementation(async(_p:string,id:string)=>detail(id));await f.store.refresh();await f.store.selectRecord(from);let release:any;f.api.detail.mockImplementation((_p:string,id:string)=>id===to?new Promise(r=>release=()=>r(detail(id))):Promise.resolve(detail(id)));const pending=f.store.selectRecord(to);await vi.waitFor(()=>expect(release).toBeTypeOf('function'));const confirming=f.store.confirm(true);const cancelling=f.store.cancel();expect(f.api.confirm).not.toHaveBeenCalled();expect(f.api.cancel).not.toHaveBeenCalled();release();await pending;await confirming;await cancelling;f.api.detail.mockImplementation(async(_p:string,id:string)=>detail(id));await f.store.confirm(true);expect(f.api.confirm).toHaveBeenCalledWith('p',to,expect.any(Object));});

for(const mode of ['latest_without_active','latest_with_active','active_replaced'])it('服务端版本更替后同步选择并恢复操作 '+mode,async()=>{const f=setup();const snap=(active:string|null,latest:string)=>({project_id:'p',active_narration:active?{narration_record_id:active}:null,latest_narration_candidate:{narration_record_id:latest}});f.api.snapshot.mockResolvedValue(snap('a','b'));f.api.detail.mockImplementation(async(_p:string,id:string)=>({record:{id,sourceTextSha256:context.source_text_sha256,settingsSha256:'b'.repeat(64)},effective_status:'ready',files:null}));await f.store.refresh();await f.store.selectRecord(mode==='active_replaced'?'a':'b');f.api.snapshot.mockResolvedValue(mode==='active_replaced'?snap('c','c'):snap(mode==='latest_with_active'?'a':null,'c'));await f.store.refresh();expect(f.store.state.detail?.record.id).toBe('c');expect(f.store.state.selectedRecordId).toBe('c');await f.store.confirm(true);expect(f.api.confirm).toHaveBeenCalledWith('p','c',expect.any(Object));await f.store.cancel();expect(f.api.cancel).toHaveBeenCalledWith('p','c');});
