// @vitest-environment jsdom
import {mount,flushPromises} from '@vue/test-utils';
import {expect,it,vi} from 'vitest';
import {reactive} from 'vue';
import NarrationPanel from '../../frontend/src/components/script/NarrationPanel.vue';
function setup(status='ready'){const store:any={state:reactive({busy:false,loading:false,error:null,context:{options:[{provider_model_id:'q',voice_profile_id:'v',model:'Qwen',voice:'木灵',supported_tones:['neutral'],supported_rates:[1]}],configuration:{capabilities:{'tts.synthesize':{provider_model_id:'q'}},creative:{voice_profile_id:'v'}},target_duration_band:{minMs:1000,maxMs:5000}},snapshot:{script_confirmation:{},narration_readiness:{ready:false}},detail:{effective_status:status,record:{id:'n',settings:{model:'Qwen',voice:'木灵'},output:{durationMs:6000}},files:{audio:'/audio'},subtitle:null}}),refresh:vi.fn(),generate:vi.fn(),confirm:vi.fn(),cancel:vi.fn(),saveSettings:vi.fn(),confirmScript:vi.fn(),canProceed:()=>store.state.snapshot.narration_readiness.ready};return {store,w:mount(NarrationPanel,{props:{store,estimatedDurationSec:4}})};}
it('超时长必须明确接受后确认',async()=>{const {w,store}=setup();expect(w.text()).toContain('超出目标区间');expect(w.get('[data-testid=narration-confirm]').attributes('disabled')).toBeDefined();await w.get('[data-testid=accept-duration]').setValue(true);await w.get('[data-testid=narration-confirm]').trigger('click');expect(store.confirm).toHaveBeenCalledWith(true);w.unmount();});
for(const status of ['generating','failed','cancelled','unknown','stale'])it('状态明确展示 '+status,()=>{const {w}=setup(status);expect(w.get('[data-testid=narration-status]').text()).toBeTruthy();expect(w.find('[data-testid=narration-confirm]').exists()).toBe(false);w.unmount();});
it('能力表驱动参数且取消编辑不保存',async()=>{const {w,store}=setup();await w.get('[data-testid=edit-narration-settings]').trigger('click');expect(w.get('[data-testid=narration-tone]').attributes('disabled')).toBeDefined();await w.get('[data-testid=cancel-settings]').trigger('click');expect(store.saveSettings).not.toHaveBeenCalled();w.unmount();});

it('控件按资格能力响应，不硬编码音色名称',async()=>{const {w,store}=setup();store.state.context.options=[{provider_model_id:'other',voice_profile_id:'other-voice',model:'已合格模型',voice:'任意音色',supported_tones:['neutral','happy'],supported_rates:[1,1.1]}];await w.get('[data-testid=edit-narration-settings]').trigger('click');expect(w.get('[data-testid=narration-tone]').attributes('disabled')).toBeUndefined();expect(w.get('[data-testid=narration-tone]').findAll('option')).toHaveLength(2);w.unmount();});

for(const within of [true,false])it('已确认音频目标区间变化后零生成重新确认 '+within,async()=>{const {w,store}=setup('confirmed');store.state.snapshot.narration_readiness={ready:false,reason:'narration_duration_not_accepted'};store.state.context.target_duration_band=within?{minMs:1000,maxMs:7000}:{minMs:1000,maxMs:5000};await flushPromises();expect(w.find('[data-testid=narration-confirm]').exists()).toBe(true);if(!within)await w.get('[data-testid=accept-duration]').setValue(true);store.confirm.mockImplementation(async()=>{store.state.snapshot.narration_readiness={ready:true};});await w.get('[data-testid=narration-confirm]').trigger('click');await flushPromises();expect(store.confirm).toHaveBeenCalledWith(!within);expect(store.generate).not.toHaveBeenCalled();expect(w.emitted('proceed')).toHaveLength(1);w.unmount();});
for(const code of ['narration_timing_invalid','narration_provider_unknown'])it('恢复失败原因 '+code,async()=>{const {w,store}=setup('failed');store.state.detail.record.errorCode=code;await flushPromises();expect(w.get('[data-testid=narration-failure-reason]').text()).toBeTruthy();w.unmount();});

for(const intermediate of [false,true])it('目标区间变化清除旧超时长同意 '+intermediate,async()=>{const {w,store}=setup();await w.get('[data-testid=accept-duration]').setValue(true);if(intermediate){store.state.context.target_duration_band={minMs:1000,maxMs:7000};await flushPromises();}store.state.context.target_duration_band={minMs:2000,maxMs:4000};await flushPromises();expect((w.get('[data-testid=accept-duration]').element as HTMLInputElement).checked).toBe(false);expect(w.get('[data-testid=narration-confirm]').attributes('disabled')).toBeDefined();w.unmount();});
