import {expect,it,vi} from 'vitest';
import {createNarrationStore} from '../../frontend/src/stores/narration';
const context:any={mode:'narration_first_v1',source_script_record_id:'s',source_text_sha256:'a'.repeat(64),configuration_revision:1,target_duration_band:{minMs:1000,maxMs:5000},options:[],configuration:{creative:{},video:{},capabilities:{}}};
function setup(){let project='p';const api:any={context:vi.fn(async()=>context),snapshot:vi.fn(async()=>({project_id:project,narration_readiness:{ready:false},latest_narration_candidate:null})),detail:vi.fn(),generate:vi.fn(async()=>({narration_record_id:'n'})),confirmScript:vi.fn(),confirm:vi.fn(),cancel:vi.fn(),save:vi.fn()};return {api,setProject:(p:string)=>project=p,store:createNarrationStore({projectId:()=>project,api,keyStore:new Map()})};}
it('重复点击只发一次，网络失败重试同key',async()=>{const f=setup();await f.store.refresh();f.api.generate.mockRejectedValueOnce(Error('network'));await Promise.all([f.store.generate(),f.store.generate()]);expect(f.api.generate).toHaveBeenCalledTimes(1);const key=f.api.generate.mock.calls[0][1].idempotency_key;await f.store.generate();expect(f.api.generate.mock.calls[1][1].idempotency_key).toBe(key);});
it('URL存在不能代替后端readiness',async()=>{const f=setup();await f.store.refresh();expect(f.store.canProceed()).toBe(false);f.api.snapshot.mockResolvedValue({project_id:'p',narration_readiness:{ready:true}});await f.store.refresh();expect(f.store.canProceed()).toBe(true);});
it('项目切换后旧刷新不得覆盖新项目',async()=>{const f=setup();let resolve:any;f.api.context.mockImplementationOnce(()=>new Promise(r=>resolve=r));const old=f.store.refresh();f.setProject('q');await f.store.refresh();resolve({...context,source_script_record_id:'old'});await old;expect(f.store.state.projectId).toBe('q');expect(f.store.state.context?.source_script_record_id).toBe('s');});
it('刷新恢复服务端候选状态',async()=>{const f=setup();f.api.snapshot.mockResolvedValue({project_id:'p',latest_narration_candidate:{narration_record_id:'n'}});f.api.detail.mockResolvedValue({record:{id:'n'},effective_status:'unknown',files:null});await f.store.refresh();expect(f.store.state.detail?.effective_status).toBe('unknown');expect(f.api.generate).not.toHaveBeenCalled();});

for(const status of ['unknown','failed'])it('恢复已接受终态后显式重生创建新key '+status,async()=>{const f=setup();await f.store.refresh();f.api.generate.mockRejectedValueOnce(Error('network'));await f.store.generate();const key=f.api.generate.mock.calls[0][1].idempotency_key;f.api.snapshot.mockResolvedValue({project_id:'p',latest_narration_candidate:{narration_record_id:'n'}});f.api.detail.mockResolvedValue({record:{id:'n',sourceTextSha256:context.source_text_sha256},effective_status:status,idempotency_key:key,files:null});await f.store.refresh();await f.store.generate();expect(f.api.generate.mock.calls[1][1].idempotency_key).not.toBe(key);});
