import { describe, expect, it } from "vitest";

import {
  normalizeSubtitleStyle,
  parseSubtitleCues,
} from "../../../backend/src/modules/render/subtitle-cue-reader.js";
import { DEFAULT_SUBTITLE_STYLE } from "../../../shared/src/index.js";

describe("subtitle cue reader", () => {
  it("parses SRT cues", () => {
    expect(
      parseSubtitleCues({
        format: "srt",
        content:
          "1\n00:00:00,000 --> 00:00:01,500\n第一句\n\n2\n00:00:01,500 --> 00:00:03,000\n第二句\n",
      }),
    ).toEqual([
      { start_sec: 0, end_sec: 1.5, text: "第一句" },
      { start_sec: 1.5, end_sec: 3, text: "第二句" },
    ]);
  });

  it("parses VTT cues with descriptive header and no hour field", () => {
    expect(
      parseSubtitleCues({
        format: "vtt",
        content:
          "WEBVTT - Generated by local subtitles\n\n1\n00:00.000 --> 00:02.000\nOpening pressure.\n",
      }),
    ).toEqual([
      { start_sec: 0, end_sec: 2, text: "Opening pressure." },
    ]);
  });

  it("keeps multi-line cue text", () => {
    expect(
      parseSubtitleCues({
        format: "srt",
        content:
          "1\n00:00:00,000 --> 00:00:02,000\n第一行\n第二行\n",
      }),
    ).toEqual([
      { start_sec: 0, end_sec: 2, text: "第一行\n第二行" },
    ]);
  });

  it("normalizes missing style to default style", () => {
    expect(normalizeSubtitleStyle(undefined)).toEqual(DEFAULT_SUBTITLE_STYLE);
  });

  it("normalizes invalid style to default style", () => {
    expect(
      normalizeSubtitleStyle({
        ...DEFAULT_SUBTITLE_STYLE,
        position: "below_frame",
      }),
    ).toEqual(DEFAULT_SUBTITLE_STYLE);
  });
});
