import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { EventEmitter } from 'node:events';
import { execFileSync } from 'node:child_process';
import { afterEach, describe, expect, it, vi } from 'vitest';
const entry='harness/scripts/runtime/narration-paragraph-diagnostic.ts';
async function api(){expect(existsSync(entry),'自然段诊断入口必须存在').toBe(true);return import('../../harness/scripts/runtime/narration-paragraph-diagnostic.js');}
const dirs:string[]=[];
function output(){const d=mkdtempSync(join(tmpdir(),'narration-paragraph-'));dirs.push(d);return join(d,'round');}
afterEach(()=>{vi.restoreAllMocks();for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true});});
class Socket extends EventEmitter {sent:any[]=[];failAt=0;send(s:string){if(this.failAt&&this.sent.length===this.failAt)throw Error('send');this.sent.push(JSON.parse(s));}close(){}terminate(){}}
const message=(s:Socket,event:string,payload={})=>s.emit('message',Buffer.from(JSON.stringify({header:{task_id:'t',event},payload})),false);
describe('授权两次自然段输入诊断',()=>{
 it.each([null,'provider-uuid'])('完成账本保留计划请求ID并分开供应商ID %s',async providerId=>{const q=await api();const d=output();await q.executeDiagnostic(q.buildDiagnosticPlan(),1,d,async()=>({status:'succeeded',usage_characters:3254,request_id:providerId}));const lines=readFileSync(join(d,'attempts.jsonl'),'utf8').trim().split('\n').map(x=>JSON.parse(x));expect(lines.map(x=>x.request_id)).toEqual(['cosy-sanshu:long','cosy-sanshu:long','qwen-yimuling:long','qwen-yimuling:long']);expect(lines[1].provider_request_id).toBe(providerId);expect(lines[3].provider_request_id).toBe(providerId);});
 it('CLI缺省离线、非法参数仅输出明确JSON错误',async()=>{await api();const args=['node_modules/tsx/dist/cli.mjs',entry];expect(JSON.parse(execFileSync(process.execPath,args,{encoding:'utf8'})).actual_requests).toBe(0);let failure:any;try{execFileSync(process.execPath,[...args,'--live'],{encoding:'utf8',stdio:'pipe'});}catch(e){failure=e;}expect(failure).toBeDefined();expect(JSON.parse(failure.stderr)).toEqual({error:'diagnostic_authorization_invalid'});});
 it.each(['更换全文','删掉\n原换行'])('冻结正文校验拒绝变化 %s',async text=>{const q=await api();expect(()=>q.verifyFrozenText(text)).toThrow('diagnostic_text_changed');});
 it('成功前缀后第二项失败保持已知成本，重启不重发任一项',async()=>{const q=await api();const d=output();let n=0;const transport=vi.fn(async()=>++n===1?{status:'succeeded' as const,usage_characters:3254}:{status:'failed' as const,usage_characters:3254});const r=await q.executeDiagnostic(q.buildDiagnosticPlan(),1,d,transport);expect(r.calls[0].accounted_cost_cny).toBe(.3254);expect(r.calls[1].accounted_cost_cny).toBe(.6746);expect(r.actual_cost_cny).toBeNull();expect(r.accounted_cost_cny).toBe(1);expect(r.actual_requests).toBe(2);await expect(q.executeDiagnostic(q.buildDiagnosticPlan(),1,d,transport)).rejects.toThrow();expect(transport).toHaveBeenCalledTimes(2);});
 it('缺省只输出两次同稿计划、零调用且不授资格',async()=>{const q=await api();const r=await q.runDiagnostic(q.parseDiagnosticArgs([]));expect(r.actual_requests).toBe(0);expect(r.qualification).toBe('unverified');expect(r.plan.requests.map(x=>x.id)).toEqual(['cosy-sanshu:long','qwen-yimuling:long']);expect(r.plan.scheduling_reserve_cny).toBe(.8352);expect(new Set(r.plan.requests.map(x=>x.text_sha256)).size).toBe(1);});
 it.each([['--live'],['--confirm-live'],['--live','--confirm-live','--max-requests','3','--max-cost-cny','1'],['--live','--confirm-live','--max-requests','2','--max-cost-cny','1.01'],['--live','--confirm-live','--max-requests','2','--max-cost-cny','NaN'],['--live','--confirm-live','--max-requests','2','--max-cost-cny','.8'],['--dry-run','--live'],['--output-dir','another']])('拒绝未授权/扩大/低于预留/非法参数 %j',async(...args)=>{const q=await api();expect(()=>q.parseDiagnosticArgs(args)).toThrow();});
 it('拒绝改换音色矩阵或历史费用证据',async()=>{const q=await api();const m=q.loadDiagnosticManifest();m.request_ids.reverse();expect(()=>q.buildDiagnosticPlan(m)).toThrow('diagnostic_matrix_changed');expect(()=>q.verifyBaseline(Buffer.from('{}'))).toThrow('baseline_evidence_changed');});
 it('自然段拆分逐字保留换行、空行及UTF16代理对，拒绝空正文',async()=>{const q=await api();for(const text of ['甲。\n乙。\n丙。','𠮷é。\r\n\n第12次。']){const p=q.splitParagraphs(text);expect(p.join('')).toBe(text);expect(p.every(x=>x.length>0)).toBe(true);}expect(()=>q.splitParagraphs('')).toThrow('text_empty');});
 it('一个task发送18个continue，仅一次run/finish，不重复已开始事件',async()=>{const q=await api();const s=new Socket();const text=Array.from({length:18},(_,i)=>'段落'+i+(i<17?'\n':'')).join('');const p=q.captureParagraphTask(s,q.buildDiagnosticPlan().requests[0],text,'t',1000);s.emit('open');message(s,'task-started');message(s,'task-started');expect(s.sent.map(x=>x.header.action)).toEqual(['run-task',...Array(18).fill('continue-task'),'finish-task']);expect(s.sent.slice(1,-1).map(x=>x.payload.input.text).join('')).toBe(text);expect(new Set(s.sent.map(x=>x.header.task_id))).toEqual(new Set(['t']));message(s,'result-generated',{output:{type:'sentence-begin',sentence:{index:0}}});s.emit('message',Buffer.from([1,2]),true);message(s,'result-generated',{output:{type:'sentence-end',sentence:{index:0}},usage:{characters:20}});message(s,'task-finished');const r=await p;expect(r.usage_characters).toBe(20);expect(r.outbound.filter(x=>x.action==='continue-task')).toHaveLength(18);expect(r.pcm).toEqual(Buffer.from([1,2]));});
 it.each([1,8])('分段发送中途异常不重试或finish，不复用部分计费 %i',async failAt=>{const q=await api();const s=new Socket();s.failAt=failAt;const p=q.captureParagraphTask(s,q.buildDiagnosticPlan().requests[0],Array(18).fill('甲\n').join(''),'t',1000);s.emit('open');message(s,'task-started');const r=await p;expect(r.status).toBe('unknown');expect(r.usage_characters).toBeNull();expect(s.sent.some(x=>x.header.action==='finish-task')).toBe(false);expect(s.sent).toHaveLength(failAt);});
 it('两次串行执行保留原累计费用和零评分，重复目录拒绝',async()=>{const q=await api();const d=output();const transport=vi.fn(async()=>({status:'succeeded' as const,usage_characters:3254}));const r=await q.executeDiagnostic(q.buildDiagnosticPlan(),1,d,transport);expect(transport).toHaveBeenCalledTimes(2);expect(r.actual_cost_cny).toBe(.78096);expect(r.total_usage_cost_cny).toBe(2.33198);expect(r.qualification).toBe('unverified');expect(r.recommended_candidate).toBeNull();expect(readFileSync(join(d,'attempts.jsonl'),'utf8').trim().split('\n')).toHaveLength(4);await expect(q.executeDiagnostic(q.buildDiagnosticPlan(),1,d,transport)).rejects.toThrow();expect(transport).toHaveBeenCalledTimes(2);});
 it.each(['failed','unknown','throw','invalid-usage'])('首项%s时占满本项剩余额度，不发第二项、不重试',async mode=>{const q=await api();const transport=vi.fn(async()=>{if(mode==='throw')throw Error('private');return {status:mode==='invalid-usage'?'succeeded' as const:mode as 'failed'|'unknown',usage_characters:mode==='invalid-usage'?NaN:10};});const r=await q.executeDiagnostic(q.buildDiagnosticPlan(),1,output(),transport);expect(transport).toHaveBeenCalledTimes(1);expect(r.actual_cost_cny).toBeNull();expect(r.accounted_cost_cny).toBe(1);expect(r.total_accounted_cost_cny).toBe(2.55102);expect(r.stopped_reason).toBe('unknown_cost');expect(JSON.stringify(r)).not.toContain('private');});
 it('已知首项费用增加使余额不足时不派发Qwen',async()=>{const q=await api();const transport=vi.fn(async()=>({status:'succeeded' as const,usage_characters:6000}));const r=await q.executeDiagnostic(q.buildDiagnosticPlan(),1,output(),transport);expect(transport).toHaveBeenCalledTimes(1);expect(r.actual_cost_cny).toBe(.6);expect(r.stopped_reason).toBe('cost_limit');});
 it('并发启动同一冻结输出目录只允许一个调用序列',async()=>{const q=await api();const d=output();const transport=vi.fn(async()=>({status:'succeeded' as const,usage_characters:3254}));const rs=await Promise.allSettled([q.executeDiagnostic(q.buildDiagnosticPlan(),1,d,transport),q.executeDiagnostic(q.buildDiagnosticPlan(),1,d,transport)]);expect(rs.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(transport).toHaveBeenCalledTimes(2);});
 it('直接执行也拒绝篡改计划及非法上限，零transport调用',async()=>{const q=await api();const p=q.buildDiagnosticPlan();p.requests.reverse();const transport=vi.fn();await expect(q.executeDiagnostic(p,1,output(),transport)).rejects.toThrow('diagnostic_matrix_changed');for(const cap of [NaN,Infinity,0,.8,1.1])await expect(q.executeDiagnostic(q.buildDiagnosticPlan(),cap,output(),transport)).rejects.toThrow('diagnostic_limit_invalid');expect(transport).not.toHaveBeenCalled();});
});
