<script setup lang="ts">
import { computed, onMounted, watch, ref } from "vue";
import { useRouter } from "vue-router";
import { ElMessage } from "element-plus";

import { useScriptStore } from "../../stores/script";
import { useProjectStore } from "../../stores/project";
import { useWorkspaceStore, PIPELINE_STEPS } from "../../stores/workspace";
import { useStagePolling } from "../../composables/useStagePolling";
import StageGenerating from "../workspace/StageGenerating.vue";
import StageLoadingBar from "../workspace/StageLoadingBar.vue";
import RegenFeedbackModal from "./RegenFeedbackModal.vue";

const scriptStore = useScriptStore();
const workspaceStore = useWorkspaceStore();

const STORYBOARD_STEP_INDEX = PIPELINE_STEPS.findIndex((s) => s.key === "storyboard");
const router = useRouter();
const projectStore = useProjectStore();

const { startPolling } = useStagePolling({
  loadSnapshot: () => scriptStore.loadActiveScriptSnapshot(),
  isGenerating: (snapshot) =>
    snapshot.current_status === "script_generating" ||
    snapshot.active_script?.execution_state?.generating === true,
  isTerminal: (snapshot) => {
    if (snapshot.current_status === "script_failed") return true;
    if (!snapshot.active_script) return false;
    // generating 占位记录不算终态
    if (snapshot.active_script.execution_state?.generating) return false;
    // 有真实 script_text 且状态不是 generating
    return !!snapshot.active_script.script_text;
  },
});

onMounted(async () => {
  await scriptStore.loadActiveScriptSnapshot();
  // F5 恢复：如果 snapshot 显示 generating，启动轮询
  const s = scriptStore.state.snapshot;
  if (
    s?.current_status === "script_generating" ||
    s?.active_script?.execution_state?.generating
  ) {
    startPolling();
  }
  await triggerAutoGenerate();
});

let autoGenerated = false;

/** Auto-generate script when snapshot shows ready state but no active script. */
async function triggerAutoGenerate() {
  if (autoGenerated) return;
  const s = scriptStore.state.snapshot;
  if (
    s &&
    !s.active_script &&
    (s.current_status === "script_pending" || s.current_status === "script_ready") &&
    !scriptStore.state.isLoading &&
    !scriptStore.state.loadError
  ) {
    autoGenerated = true;
    startPolling();
    await scriptStore.generateInitialScript();
    if (!scriptStore.state.loadError) {
      ElMessage.success("文案已生成");
    }
  }
}

// Also trigger on snapshot change (handles timing where projectId is set after mount)
watch(() => scriptStore.state.snapshot, async (snapshot) => {
  if (snapshot && !snapshot.active_script && !autoGenerated) {
    await triggerAutoGenerate();
  }
});

/** Resolve the visible script: selected history entry > active snapshot > fallback from history. */
const visibleScript = computed(() => {
  const selected = scriptStore.state.history.find(
    (entry) => entry.entry_id === scriptStore.state.selectedHistoryEntryId,
  );
  if (selected) return selected.script;

  if (scriptStore.state.snapshot?.active_script) {
    return scriptStore.state.snapshot.active_script;
  }

  if (
    scriptStore.state.snapshot?.current_status === "script_reviewing" ||
    scriptStore.state.snapshot?.current_status === "script_failed"
  ) {
    return scriptStore.state.history[0]?.script ?? null;
  }

  return null;
});

const isGenerating = computed(
  () =>
    scriptStore.state.snapshot?.current_status === "script_generating" ||
    scriptStore.state.snapshot?.active_script?.execution_state?.generating === true,
);

const isGenerationFailed = computed(
  () =>
    scriptStore.state.snapshot?.current_status === "script_failed",
);

const isInitialScriptLoading = computed(
  () => scriptStore.state.isLoading && !visibleScript.value,
);

const displayScriptText = computed(() => {
  const text = visibleScript.value?.script_text ?? "";

  if (text.includes("\n")) {
    return text.replace(/\n{3,}/g, "\n\n").replace(/\n(?!\n)/g, "\n\n").replace(/\n{3,}/g, "\n\n");
  }

  const sentences = text.split(/(?<=[。！？])(?=[^。！？])/);
  if (sentences.length <= 2) return text;

  const paragraphs: string[] = [];
  for (let i = 0; i < sentences.length; i += 2) {
    const chunk = sentences.slice(i, i + 2).join("");
    if (chunk.trim()) paragraphs.push(chunk);
  }
  return paragraphs.join("\n\n");
});

/** Build review soft issues list from semantic_review for display. */
const reviewIssues = computed(() => {
  const s = visibleScript.value;
  if (!s?.semantic_review) return [];

  const issues: Array<{ code: string; message: string }> = [];

  if (s.semantic_review.summary) {
    issues.push({ code: "review_summary", message: s.semantic_review.summary });
  }

  const softIssues = s.semantic_review.soft_issues ?? [];
  for (const item of softIssues) {
    if (typeof item === "string") {
      issues.push({ code: "", message: item });
    } else {
      issues.push({ code: item.code ?? "", message: item.message ?? "" });
    }
  }

  return issues;
});

const reviewDecision = computed(() => {
  const s = visibleScript.value;
  if (!s) return null;
  if (s.semantic_review?.decision) return s.semantic_review.decision;
  if (s.local_validation?.decision) return s.local_validation.decision;
  return null;
});

const scriptWordCount = computed(() => {
  const text = visibleScript.value?.script_text ?? "";
  return text.replace(/\s/g, "").length;
});

const scriptDurationSec = computed(() => {
  return visibleScript.value?.estimated_duration_sec ?? 0;
});

const scriptDurationLabel = computed(() => {
  const sec = scriptDurationSec.value;
  if (!sec) return "—";
  const m = Math.floor(sec / 60);
  const s = sec % 60;
  return m > 0 ? `约${m}分${s}秒` : `约${s}秒`;
});

const visibleScriptVersionLabel = computed(() => {
  const total = scriptStore.state.history.length;
  if (total === 0) return "首稿";
  const selected = historyEntries.value.find(
    (e) => e.entry_id === scriptStore.state.selectedHistoryEntryId,
  );
  if (selected) return selected.versionLabel;
  return total === 1 ? "首稿" : `V${total}`;
});

const isViewingHistoryEntry = computed(() => {
  const entries = scriptStore.state.history;
  if (entries.length === 0) return false;
  return scriptStore.state.selectedHistoryEntryId !== entries[0]?.entry_id;
});

const viewingHistoryLabel = computed(() => {
  if (!isViewingHistoryEntry.value) return null;
  const entry = historyEntries.value.find(
    (e) => e.entry_id === scriptStore.state.selectedHistoryEntryId,
  );
  if (!entry) return null;
  return entry.versionLabel;
});

const scriptCreatedAtLabel = computed(() => {
  const iso = visibleScript.value?.created_at;
  if (!iso) return null;
  const d = new Date(iso);
  const now = new Date();
  const isToday = d.toDateString() === now.toDateString();
  const time = d.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" });
  if (isToday) return `今天 ${time}`;
  return `${d.getMonth() + 1}/${d.getDate()} ${time}`;
});

function formatHistoryTime(iso?: string) {
  if (!iso) return null;
  const d = new Date(iso);
  const now = new Date();
  const isToday = d.toDateString() === now.toDateString();
  const time = d.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" });
  if (isToday) return `今天 ${time}`;
  return `${d.getMonth() + 1}/${d.getDate()} ${time}`;
}

function historyReviewBadge(decision?: string) {
  if (decision === "pass") return { text: "通过", type: "success" as const };
  if (decision === "regen_once") return { text: "建议重生成", type: "warning" as const };
  if (decision === "hard_fail") return { text: "未通过", type: "danger" as const };
  return { text: "审校中", type: "info" as const };
}

function historyPreview(text: string) {
  return text.replace(/\s/g, "").slice(0, 40);
}

const ISSUE_CODE_MAP: Record<string, string> = {
  scene_enhancement: "场景细节",
  dialogue_enhancement: "对话细节",
  opening_hook_weak: "开篇冲击力",
  pace_too_slow: "节奏偏慢",
  pace_too_fast: "节奏偏快",
  emotional_depth: "情感厚度",
  character_depth: "人物刻画",
  ending_weak: "结尾力度",
  script_body_too_thin: "篇幅偏薄",
  conflict_pressure: "冲突压力",
};

function humanizeIssueCode(code: string) {
  return ISSUE_CODE_MAP[code] ?? code;
}

const historyEntries = computed(() => {
  const total = scriptStore.state.history.length;
  return scriptStore.state.history.map((entry, idx) => {
    const versionNum = total - idx;
    return {
      entry_id: entry.entry_id,
      label: entry.label,
      version: versionNum,
      versionLabel: versionNum === 1 ? "首稿" : `V${versionNum}`,
      script_text: entry.script.script_text,
      word_count: entry.script.script_text.replace(/\s/g, "").length,
      review_decision: entry.script.review_decision,
      created_at: entry.script.created_at,
      execution_state: entry.script.execution_state,
    };
  });
});

const showRegenModal = ref(false);
const isRegenerating = ref(false);
const historyOpen = ref(false);

function toggleHistory() {
  historyOpen.value = !historyOpen.value;
}

async function handleRegenSubmit(userFeedback: string) {
  isRegenerating.value = true;
  try {
    await scriptStore.runRegenOnce(userFeedback || undefined);
    if (!scriptStore.state.loadError) {
      ElMessage.success("文案重新生成完成");
    }
  } finally {
    isRegenerating.value = false;
  }
}

function handleRetry() {
  scriptStore.retryLoadActiveScriptSnapshot();
}

function handleSelectHistory(entryId: string) {
  scriptStore.selectHistoryEntry(entryId);
}

function handleConfirm() {
  ElMessage.success("文案已确认，进入分镜规划");
  workspaceStore.setCurrentStep(STORYBOARD_STEP_INDEX);
  const pid = projectStore.state.projectId; if (pid) router.push(`/projects/${pid}/storyboard`);
}
</script>

<template>
  <div class="script-panel">
    <div v-if="scriptStore.state.loadError" class="script-error-card">
      <el-alert
        :title="'加载失败：' + scriptStore.state.loadError"
        type="error"
        show-icon
        :closable="false"
      />
      <el-button
        type="primary"
        :loading="scriptStore.state.isLoading"
        @click="handleRetry"
      >
        重试
      </el-button>
    </div>

    <!-- Generating state (before skeleton to show explanation during generation) -->
    <StageGenerating
      v-else-if="isGenerating && !isRegenerating"
      title="正在生成文案"
      hint="正在调用大模型撰写口播文案，可能需要 1-3 分钟。"
      secondary-hint="页面会自动刷新，也可手动刷新状态。"
    >
      <template #action>
        <el-button
          :loading="scriptStore.state.isLoading"
          @click="scriptStore.retryLoadActiveScriptSnapshot()"
        >
          手动刷新
        </el-button>
      </template>
    </StageGenerating>

    <!-- Loading skeleton (only when loading without active generation) -->
    <el-skeleton
      v-else-if="isInitialScriptLoading"
      :rows="6"
      animated
      class="script-skeleton"
    />

    <!-- Generation failed state -->
    <div v-else-if="isGenerationFailed" class="script-failed">
      <p>文案生成失败，请重试或返回选题重新确认。</p>
      <el-button type="primary" @click="handleRetry">重试</el-button>
    </div>

    <!-- Main two-column layout -->
    <template v-else-if="visibleScript">
      <h1 class="script-page-title">请审校您的<em>文案</em></h1>
      <div class="script-columns">
        <!-- Left column: Script text -->
        <div class="script-left-col">
          <div class="script-text-card">
            <div v-if="viewingHistoryLabel" class="script-history-banner">
              📋 查看历史版本 · {{ viewingHistoryLabel }}
            </div>
            <div class="script-text-body" data-testid="script-text-body">
              {{ displayScriptText }}
            </div>
          </div>

          <!-- History versions -->
          <div v-if="historyEntries.length > 0" class="script-history">
            <div class="script-history-top">
              <button class="history-toggle-btn" @click="toggleHistory">
                <span class="toggle-arrow" :class="{ open: historyOpen }">▶</span>
                历史版本（{{ historyEntries.length }}）
              </button>
              <button
                class="history-regen-btn"
                :disabled="scriptStore.state.isRunningAction || isViewingHistoryEntry"
                @click="showRegenModal = true"
              >
                {{ scriptStore.state.isRunningAction ? "处理中..." : "↺ 重新生成" }}
              </button>
            </div>
            <div v-if="historyOpen" class="script-history-list">
              <div
                v-for="entry in historyEntries"
                :key="entry.entry_id"
                class="script-history-item"
                :class="{
                  'script-history-item--active':
                    scriptStore.state.selectedHistoryEntryId === entry.entry_id,
                }"
                @click="handleSelectHistory(entry.entry_id)"
              >
                <div class="script-history-preview">
                  {{ historyPreview(entry.script_text) }}
                </div>
                <div class="script-history-meta">
                  <span class="script-history-version">{{ entry.versionLabel }}</span>
                  <span>{{ entry.word_count }}字</span>
                  <el-tag
                    :type="historyReviewBadge(entry.review_decision).type"
                    size="small"
                  >
                    {{ historyReviewBadge(entry.review_decision).text }}
                  </el-tag>
                  <span v-if="entry.created_at">{{ formatHistoryTime(entry.created_at) }}</span>
                  <el-tag
                    v-if="entry.entry_id === historyEntries[0]?.entry_id"
                    size="small"
                    type="warning"
                  >
                    当前
                  </el-tag>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Right column: Review & Actions -->
        <div class="script-right-col">
          <!-- Script info -->
          <div class="script-info-card">
            <span class="script-info-stat">{{ visibleScriptVersionLabel }}</span>
            <span class="script-info-divider"></span>
            <span class="script-info-stat">{{ scriptWordCount }}字</span>
            <span class="script-info-divider"></span>
            <span class="script-info-stat">{{ scriptDurationLabel }}</span>
            <span v-if="scriptCreatedAtLabel" class="script-info-stat script-info-time">{{ scriptCreatedAtLabel }}</span>
          </div>

          <!-- Review results -->
          <div v-if="reviewIssues.length > 0" class="script-review-card">
            <h3 class="script-review-heading">
              审校建议
              <el-tag
                v-if="reviewDecision === 'pass'"
                size="small"
                type="success"
              >
                通过
              </el-tag>
              <el-tag
                v-else-if="reviewDecision === 'regen_once'"
                size="small"
                type="warning"
              >
                建议重生成
              </el-tag>
              <el-tag
                v-else-if="reviewDecision"
                size="small"
                type="danger"
              >
                需修改
              </el-tag>
            </h3>
            <div
              v-for="(issue, idx) in reviewIssues"
              :key="idx"
              class="script-review-issue"
            >
              <span
                v-if="issue.code === 'review_summary'"
                class="script-review-summary"
              ><span class="script-review-issue-code">摘要</span>{{ issue.message }}</span>
              <template v-else>
                <span
                  v-if="issue.code"
                  class="script-review-issue-code"
                >{{ humanizeIssueCode(issue.code) }}</span>
                <span class="script-review-issue-msg">{{ issue.message }}</span>
              </template>
            </div>
          </div>

          <!-- Action buttons -->
          <div v-if="visibleScript && !isViewingHistoryEntry" class="script-actions-card">
            <el-button
              type="primary"
              :disabled="scriptStore.state.isRunningAction"
              @click="handleConfirm"
              class="script-confirm-btn"
            >
              确认文案，进入分镜规划
            </el-button>
          </div>
        </div>
      </div>
    </template>

    <RegenFeedbackModal
      :visible="showRegenModal"
      :script="visibleScript"
      @update:visible="showRegenModal = $event"
      @submit="handleRegenSubmit"
    />

    <StageLoadingBar
      :visible="isRegenerating"
      text="重新生成中…"
    />
  </div>
</template>

<style scoped>
.script-panel {
  display: grid;
  gap: var(--space-md);
  padding: var(--space-lg);
  max-width: 1280px;
  margin: 0 auto;
  width: 100%;
}

/* Error card */
.script-error-card {
  display: grid;
  gap: var(--space-md);
  padding: var(--space-md);
  border-radius: var(--radius-card);
  background: var(--bg-card);
}

/* Skeleton */
.script-skeleton {
  padding: var(--space-md);
}

/* Generating / failed */
.script-failed {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: var(--space-md);
  padding: var(--space-xl) var(--space-md);
  color: var(--text-secondary);
  text-align: center;
}

/* Two-column layout */
.script-columns {
  display: grid;
  grid-template-columns: 1.8fr 1fr;
  gap: var(--space-lg);
  align-items: start;
}

/* Page title */
.script-page-title {
  margin: 0 0 18px;
  color: var(--text-primary);
  font-family: var(--font-serif);
  font-size: 28px;
  line-height: 1.25;
  letter-spacing: -.02em;
  font-weight: 700;
}

.script-page-title em {
  color: var(--accent-gold-light);
  font-style: normal;
}

/* Left column */
.script-left-col {
  display: grid;
  gap: var(--space-md);
}

/* Script text card — single clean block */
.script-text-card {
  padding: var(--space-lg);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-panel);
  background: var(--bg-card);
}

.script-history-banner {
  margin: calc(-1 * var(--space-lg)) calc(-1 * var(--space-lg)) var(--space-lg);
  padding: 8px var(--space-lg);
  background: rgba(201, 162, 39, 0.08);
  border-bottom: 1px solid rgba(201, 162, 39, 0.15);
  font-size: 0.82rem;
  color: var(--accent-primary);
  font-weight: var(--font-subheading);
}

.script-text-body {
  margin: 0;
  color: var(--text-body);
  font-size: 1.02rem;
  line-height: 1.75;
  white-space: pre-wrap;
  letter-spacing: 0.01em;
}

/* Script info card — compact stats in right column */
.script-info-card {
  display: flex;
  align-items: center;
  gap: var(--space-sm);
  padding: 8px var(--space-md);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-panel);
  background: var(--bg-card);
  font-size: 0.82rem;
  color: var(--text-secondary);
}

.script-info-stat {
  color: var(--text-body);
  font-weight: var(--font-subheading);
}

.script-info-dim {
  color: var(--text-muted);
  font-weight: var(--font-body);
}

.script-info-time {
  margin-left: auto;
}

.script-info-divider {
  width: 1px;
  height: 14px;
  background: var(--border-default);
  flex-shrink: 0;
}

/* History */
.script-history {
  display: grid;
  gap: var(--space-sm);
  padding: var(--space-md);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-panel);
  background: var(--bg-card);
}

.script-history-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.history-toggle-btn {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 0;
  background: none;
  border: none;
  color: var(--text-secondary);
  font-size: 0.88rem;
  font-weight: var(--font-subheading);
  font-family: var(--font-family);
  cursor: pointer;
  transition: color 160ms ease;
}

.history-toggle-btn:hover {
  color: var(--text-heading);
}

.toggle-arrow {
  display: inline-block;
  font-size: 10px;
  transition: transform 200ms ease;
}

.toggle-arrow.open {
  transform: rotate(90deg);
}

.history-regen-btn {
  padding: 4px 12px;
  background: none;
  border: 1px solid var(--border-default);
  border-radius: var(--radius-sm);
  color: var(--text-secondary);
  font-size: 0.8rem;
  font-family: var(--font-family);
  cursor: pointer;
  transition: all 160ms ease;
}

.history-regen-btn:hover {
  border-color: var(--border-hover);
  color: var(--text-body);
  background: var(--bg-hover);
}

.history-regen-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.script-history-list {
  display: grid;
  gap: var(--space-xs);
}

.script-history-item {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: var(--space-sm) var(--space-md);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-card);
  background: var(--bg-panel);
  cursor: pointer;
  transition:
    border-color 160ms ease,
    background-color 160ms ease;
}

.script-history-item:hover {
  border-color: var(--border-hover);
  background: var(--bg-hover);
}

.script-history-item--active {
  border-color: var(--accent-primary);
  background: var(--bg-hover);
  box-shadow: 0 0 0 1px var(--accent-primary);
}

.script-history-preview {
  font-size: 0.84rem;
  color: var(--text-body);
  line-height: 1.5;
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
}

.script-history-version {
  display: inline-block;
  font-size: 0.7rem;
  font-weight: var(--font-subheading);
  color: var(--accent-primary);
  background: rgba(201, 162, 39, 0.12);
  padding: 1px 5px;
  border-radius: 3px;
  margin-right: 6px;
  vertical-align: middle;
}

.script-history-meta {
  display: flex;
  align-items: center;
  gap: var(--space-sm);
  font-size: 0.75rem;
  color: var(--text-muted);
}

/* Right column */
.script-right-col {
  display: grid;
  gap: var(--space-md);
  position: sticky;
  top: var(--space-md);
}

/* Review card */
.script-review-card {
  display: grid;
  gap: var(--space-md);
  padding: var(--space-lg);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-panel);
  background: var(--bg-card);
}

.script-review-heading {
  margin: 0;
  font-size: 0.95rem;
  font-weight: var(--font-subheading);
  color: var(--text-heading);
  display: flex;
  align-items: center;
  gap: var(--space-sm);
}

.script-review-issue {
  padding: var(--space-sm) 0;
  border-bottom: 1px solid var(--border-default);
  font-size: 0.88rem;
  color: var(--text-secondary);
  line-height: 1.6;
}

.script-review-issue:last-child {
  border-bottom: none;
  padding-bottom: 0;
}

.script-review-issue-code {
  display: inline-block;
  font-size: 0.7rem;
  font-weight: var(--font-subheading);
  color: var(--accent-primary);
  background: rgba(201, 162, 39, 0.12);
  padding: 1px 6px;
  border-radius: 4px;
  margin-right: 6px;
  vertical-align: middle;
}

.script-review-summary {
  color: var(--text-body);
}

.script-review-issue-msg {
  color: var(--text-secondary);
}

/* Actions card */
.script-actions-card {
  display: flex;
  gap: var(--space-sm);
  align-items: center;
  padding: var(--space-md);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-panel);
  background: var(--bg-card);
}

.script-confirm-btn {
  flex: 1;
  background: linear-gradient(135deg, #c9a227, #b87333) !important;
  border-color: transparent !important;
  color: #100c08 !important;
}

.script-confirm-btn:hover {
  background: linear-gradient(135deg, #e4c26f, #cd7f32) !important;
  border-color: transparent !important;
  filter: brightness(1.05);
}

.script-confirm-btn:active {
  background: linear-gradient(135deg, #b8931f, #a46328) !important;
}

.script-confirm-btn.is-disabled {
  background: rgba(201, 162, 39, 0.3) !important;
  border-color: transparent !important;
  color: rgba(16, 12, 8, 0.5) !important;
  cursor: not-allowed;
}

/* Responsive */
@media (max-width: 819px) {
  .script-columns {
    grid-template-columns: 1fr;
  }

  .script-right-col {
    position: static;
  }
}
</style>
