import {reactive,readonly,toRaw} from 'vue';
import {apiFetch} from '../utils/api';
import type {NarrationUiContext} from '../../../shared/src/narration/narration-ui.schema';
import type {NarrationRecord,NarrationSubtitleRevision,NarrationSubtitleTimelineV1,GenerateNarrationRequest,ConfirmNarrationRequest} from '../../../shared/src';
export interface NarrationSnapshot {project_id:string;narration_timing_mode?:string;script_confirmation?:unknown;narration_readiness?:{ready:boolean;reason:string|null};narration_subtitle_readiness?:{ready:boolean;reason:string|null};active_narration?:{narration_record_id:string}|null;latest_narration_candidate?:{narration_record_id:string;effective_status?:NarrationRecord['status']}|null;active_storyboard?:unknown;}
export interface NarrationDetail {record:NarrationRecord;effective_status:NarrationRecord['status'];run_status:string|null;idempotency_key?:string|null;files:{audio:string;timing:string;events:string;srt:string;vtt:string}|null;subtitle:{revision:NarrationSubtitleRevision;timeline:NarrationSubtitleTimelineV1}|null;}
export interface NarrationApi {context(p:string):Promise<NarrationUiContext>;snapshot(p:string):Promise<NarrationSnapshot>;detail(p:string,id:string):Promise<NarrationDetail>;generate(p:string,body:GenerateNarrationRequest):Promise<{narration_record_id:string}>;confirmScript(p:string,id:string,hash:string):Promise<unknown>;confirm(p:string,id:string,body:ConfirmNarrationRequest):Promise<unknown>;cancel(p:string,id:string):Promise<unknown>;save(p:string,body:unknown):Promise<unknown>;}
const base=(p:string)=>'/api/projects/'+encodeURIComponent(p);
export function createFetchNarrationApi():NarrationApi{return {context:p=>apiFetch(base(p)+'/script/narration/context'),snapshot:p=>apiFetch(base(p)),detail:(p,id)=>apiFetch(base(p)+'/script/narrations/'+encodeURIComponent(id)),generate:(p,body)=>apiFetch(base(p)+'/script/narration/generate',{method:'POST',body}),confirmScript:(p,id,hash)=>apiFetch(base(p)+'/script/'+encodeURIComponent(id)+'/confirm',{method:'POST',body:{source_text_sha256:hash}}),confirm:(p,id,body)=>apiFetch(base(p)+'/script/narrations/'+encodeURIComponent(id)+'/confirm',{method:'POST',body}),cancel:(p,id)=>apiFetch(base(p)+'/script/narrations/'+encodeURIComponent(id)+'/cancel',{method:'POST',body:{}}),save:(p,body)=>apiFetch(base(p)+'/generation-configuration',{method:'PATCH',body})};}
export function createNarrationStore(input:{projectId:()=>string|null;api?:NarrationApi;keyStore?:Map<string,string>}){
 const api=input.api??createFetchNarrationApi();const keys=input.keyStore??new Map<string,string>();
 const state=reactive({projectId:null as string|null,selectedRecordId:null as string|null,context:null as NarrationUiContext|null,snapshot:null as NarrationSnapshot|null,detail:null as NarrationDetail|null,error:null as string|null,loading:false,busy:false});let epoch=0;let action=0;
 const valid=(p:string,e:number)=>input.projectId()===p&&epoch===e;
 async function refresh(clearSource=false){const p=input.projectId(),e=++epoch;if(clearSource){state.selectedRecordId=null;state.context=null;state.snapshot=null;state.detail=null;}if(state.projectId!==p){state.projectId=p;state.selectedRecordId=null;state.context=null;state.snapshot=null;state.detail=null;state.error=null;}if(!p)return;state.loading=true;
 try{const [context,snapshot]=await Promise.all([api.context(p),api.snapshot(p)]);const latestId=snapshot.latest_narration_candidate?.narration_record_id,activeId=snapshot.active_narration?.narration_record_id;const id=state.selectedRecordId&&[latestId,activeId].includes(state.selectedRecordId)?state.selectedRecordId:latestId??activeId;const [detail,otherCandidate]=await Promise.all([id?api.detail(p,id):null,latestId&&latestId!==id?api.detail(p,latestId):null]);const acceptedRequest=otherCandidate??detail;if(valid(p,e)){state.context=context;state.snapshot=snapshot;state.selectedRecordId=id??null;state.detail=detail;state.error=null;
 if(acceptedRequest?.idempotency_key&&acceptedRequest.record.sourceTextSha256===context.source_text_sha256){const fingerprint=[p,context.source_script_record_id,context.source_text_sha256,context.configuration_revision].join(":");let saved=keys.get(fingerprint);try{saved??=sessionStorage.getItem("narration:"+fingerprint)??undefined;}catch{}if(saved===acceptedRequest.idempotency_key){keys.delete(fingerprint);try{sessionStorage.removeItem("narration:"+fingerprint);}catch{}}}}}
 catch(error){if(valid(p,e)){state.error=error instanceof Error?error.message:'口播状态加载失败';state.snapshot=null;}}
 finally{if(valid(p,e))state.loading=false;}}
 async function perform(fn:(p:string)=>Promise<void>){if(state.busy)return;const p=input.projectId();if(!p)return;const a=++action;state.busy=true;state.error=null;try{await fn(p);if(input.projectId()===p)await refresh();}catch(error){if(input.projectId()===p)state.error=error instanceof Error?error.message:'口播操作失败';}finally{if(a===action)state.busy=false;}}
 async function selectRecord(id:string){if(![state.snapshot?.active_narration?.narration_record_id,state.snapshot?.latest_narration_candidate?.narration_record_id].includes(id))return;state.selectedRecordId=id;await refresh();}
 function canProceed(){return state.projectId===input.projectId()&&state.snapshot?.narration_readiness?.ready===true&&!state.error;}
 async function confirmScript(){const c=state.context;if(!c?.source_script_record_id||!c.source_text_sha256)return;await perform(p=>api.confirmScript(p,c.source_script_record_id!,c.source_text_sha256!).then(()=>{}));}
 async function generate(){const c=state.context;if(!c?.source_script_record_id)return;if(state.snapshot?.latest_narration_candidate?.effective_status==='generating'){state.error='当前已有口播生成进行中，请等待其完成或取消后再试';return;}const fingerprint=[input.projectId(),c.source_script_record_id,c.source_text_sha256,c.configuration_revision].join(':');let key=keys.get(fingerprint);try{key??=sessionStorage.getItem('narration:'+fingerprint)??undefined;}catch{}key??=crypto.randomUUID();keys.set(fingerprint,key);try{sessionStorage.setItem('narration:'+fingerprint,key);}catch{}const body:GenerateNarrationRequest={source_script_record_id:c.source_script_record_id,expected_configuration_revision:c.configuration_revision,idempotency_key:key};await perform(async p=>{const result=await api.generate(p,body);if(input.projectId()===p)state.selectedRecordId=result.narration_record_id;keys.delete(fingerprint);try{sessionStorage.removeItem('narration:'+fingerprint);}catch{}});}
 function selectedDetail(){const d=state.detail;return !state.loading&&!state.error&&state.projectId===input.projectId()&&d&&(!state.selectedRecordId||state.selectedRecordId===d.record.id)?d:null;}
 async function confirm(acceptOutside:boolean){const c=state.context,d=selectedDetail();if(!c?.target_duration_band||!d)return;await perform(async p=>{await api.confirm(p,d.record.id,{source_text_sha256:d.record.sourceTextSha256,settings_sha256:d.record.settingsSha256,expected_active_narration_record_id:state.snapshot?.active_narration?.narration_record_id??null,target_duration_band_snapshot:c.target_duration_band!,accept_duration_outside_band:acceptOutside});});}
 async function cancel(){const d=selectedDetail();if(d)await perform(p=>api.cancel(p,d.record.id).then(()=>{}));}
 async function saveSettings(selection:{provider_model_id:string;voice_profile_id:string;tone:string;rate:number}){const c=state.context;if(!c?.configuration)return;const cfg=structuredClone(toRaw(c.configuration));cfg.capabilities['tts.synthesize']={mode:'fixed',provider_model_id:selection.provider_model_id};cfg.creative.voice_profile_id=selection.voice_profile_id;cfg.creative.narration={tone:selection.tone as 'neutral',rate:selection.rate as 1};await perform(p=>api.save(p,{expected_revision:c.configuration_revision,video:cfg.video,creative:cfg.creative,capabilities:cfg.capabilities}).then(()=>{}));}
 return {state:readonly(state),refresh,selectRecord,canProceed,confirmScript,generate,confirm,cancel,saveSettings};
}
export type NarrationStore=ReturnType<typeof createNarrationStore>;
