import type { VoiceProfile } from "../../../../../shared/src/index.js";

const SEED_CREATED_AT = "2026-05-19T00:00:00.000Z";
const DESIGNED_VOICE_TARGET_MODEL = "qwen3-tts-vd-2026-01-26";
const SYSTEM_TTS_MODEL = "qwen3-tts-instruct-flash";

export const SHARED_VOICE_PROFILE_SEEDS: VoiceProfile[] = [
  {
    voice_profile_id: "voice_preset_cold_authority",
    kind: "preset",
    name: "冷峻权谋型",
    description: "冷静、有压迫感的历史权谋旁白。",
    design_prompt:
      "35 到 45 岁偏男中低音，声线收紧，低沉克制，重音明确，停顿短促，情绪冷静而有压迫感，适合权谋、战争、内幕和高风险叙事。避免怒吼、恐吓腔、舞台表演感和过重气泡音。",
    preview_text:
      "诏令还没出宫门，刀兵就先到了阶下。所有人都知道要出事，只是不知道谁会先付代价。",
    provider_name: "dashscope",
    provider_voice_id: null,
    provider_status: "missing",
    target_model: DESIGNED_VOICE_TARGET_MODEL,
    recommended_content_families: [
      "historical_power",
      "historical-story",
      "war",
      "inside_story",
    ],
    voice_traits: ["cold", "authoritative", "restrained"],
    avoid_traits: ["shouting", "stage_acting", "heavy_vocal_fry"],
    gender_tone: "male_leaning",
    age_band: "35-45",
    pitch: "mid_low",
    pace: "medium_slow",
    energy: 0.45,
    authority: 0.9,
    suspense: 0.7,
    warmth: 0.2,
    preview_audio_uri: null,
    usage_count: 0,
    last_used_at: null,
    quality_score: null,
    created_at: SEED_CREATED_AT,
    updated_at: SEED_CREATED_AT,
  },
  {
    voice_profile_id: "voice_preset_steady_documentary",
    kind: "preset",
    name: "纪实沉稳型",
    description: "成熟、稳定、克制的纪实旁白。",
    design_prompt:
      "30 到 40 岁成熟中性偏男声，中低音，音色干净厚实，吐字清楚，语速中速偏慢，停连自然，情绪克制稳定，适合纪实解说、历史复盘和通识讲述。避免油腻磁性、夸张播音腔和过度戏剧化。",
    preview_text:
      "旧城门外的风沙刚落，案上的文书已经改了三次。真正改变局势的，往往不是喧闹，而是最后一句定论。",
    provider_name: "dashscope",
    provider_voice_id: null,
    provider_status: "missing",
    target_model: DESIGNED_VOICE_TARGET_MODEL,
    recommended_content_families: [
      "documentary",
      "historical_recap",
      "general_knowledge",
      "historical-story",
    ],
    voice_traits: ["steady", "documentary", "restrained", "clear"],
    avoid_traits: ["oily", "broadcast_exaggeration", "overacting"],
    gender_tone: "male_leaning",
    age_band: "30-40",
    pitch: "mid_low",
    pace: "medium_slow",
    energy: 0.4,
    authority: 0.7,
    suspense: 0.35,
    warmth: 0.35,
    preview_audio_uri: null,
    usage_count: 0,
    last_used_at: null,
    quality_score: null,
    created_at: SEED_CREATED_AT,
    updated_at: SEED_CREATED_AT,
  },
  {
    voice_profile_id: "voice_preset_crisp_storyteller",
    kind: "preset",
    name: "清朗讲述型",
    description: "清晰、亲和、节奏轻快的讲述旁白。",
    design_prompt:
      "25 到 35 岁中性偏年轻声线，中音偏亮，清晰利落，语速中速，节奏轻快但不跳脱，亲和自然，表达有层次，适合通识讲解、轻喜叙事和创意故事。避免儿童腔、卖弄感和过度活泼。",
    preview_text:
      "事情看上去只是一次小失误，可真正有意思的，是后面那串连锁反应。等你把前因后果串起来，结局就完全不一样了。",
    provider_name: "dashscope",
    provider_voice_id: null,
    provider_status: "missing",
    target_model: DESIGNED_VOICE_TARGET_MODEL,
    recommended_content_families: [
      "explainer",
      "light_comedy",
      "creative_story",
      "general_knowledge",
    ],
    voice_traits: ["crisp", "friendly", "bright", "clear"],
    avoid_traits: ["childlike", "showy", "overactive"],
    gender_tone: "neutral",
    age_band: "25-35",
    pitch: "mid_bright",
    pace: "medium",
    energy: 0.65,
    authority: 0.45,
    suspense: 0.2,
    warmth: 0.7,
    preview_audio_uri: null,
    usage_count: 0,
    last_used_at: null,
    quality_score: null,
    created_at: SEED_CREATED_AT,
    updated_at: SEED_CREATED_AT,
  },
  {
    voice_profile_id: "voice_preset_eerie_suspense",
    kind: "preset",
    name: "幽冷悬疑型",
    description: "阴冷但克制、不装神弄鬼的悬疑旁白。",
    design_prompt:
      "25 到 40 岁中性偏冷声线，中低音，气息轻，尾音收敛，语速偏慢，氛围阴冷但不装神弄鬼，适合志怪、聊斋、民俗悬疑和异闻叙事。避免鬼叫、夸张气声和影视腔式悬疑表演。",
    preview_text:
      "那条路白天并不起眼，到了夜里却没有人愿意多走一步。不是因为看见了什么，而是总有人听见身后有人轻轻叫名字。",
    provider_name: "dashscope",
    provider_voice_id: null,
    provider_status: "missing",
    target_model: DESIGNED_VOICE_TARGET_MODEL,
    recommended_content_families: [
      "folklore",
      "liaozhai",
      "weird_tales",
      "suspense",
    ],
    voice_traits: ["eerie", "suspenseful", "cool", "restrained"],
    avoid_traits: ["screaming", "exaggerated_breath", "trailer_acting"],
    gender_tone: "neutral",
    age_band: "25-40",
    pitch: "mid_low",
    pace: "slow",
    energy: 0.3,
    authority: 0.45,
    suspense: 0.9,
    warmth: 0.15,
    preview_audio_uri: null,
    usage_count: 0,
    last_used_at: null,
    quality_score: null,
    created_at: SEED_CREATED_AT,
    updated_at: SEED_CREATED_AT,
  },
  {
    voice_profile_id: "voice_system_ethan",
    kind: "system",
    name: "Ethan",
    description: "DashScope 系统兜底英文名音色，用于显式 fallback。",
    design_prompt: "系统内置 Ethan 音色，不需要供应商音色设计。",
    preview_text: "这里是系统保底音色 Ethan 的试听。",
    provider_name: "dashscope",
    provider_voice_id: "Ethan",
    provider_status: "ready",
    target_model: SYSTEM_TTS_MODEL,
    recommended_content_families: ["fallback"],
    voice_traits: ["system", "fallback"],
    avoid_traits: [],
    gender_tone: "neutral",
    age_band: null,
    pitch: "mid",
    pace: "medium",
    energy: 0.5,
    authority: 0.5,
    suspense: 0.2,
    warmth: 0.4,
    preview_audio_uri: null,
    usage_count: 0,
    last_used_at: null,
    quality_score: null,
    created_at: SEED_CREATED_AT,
    updated_at: SEED_CREATED_AT,
  },
] as const;
